/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DDay: typeof import('./../components/three-line-pic/src/DDay.vue')['default']
    DMonth: typeof import('./../components/three-line-pic/src/DMonth.vue')['default']
    FieldBox: typeof import('./../components/field-box/field-box.vue')['default']
    JDay: typeof import('./../components/three-line-pic/src/JDay.vue')['default']
    Keyboard: typeof import('./../components/field-box/keyboard.vue')['default']
    KeyboardPanel: typeof import('./../components/keyboard-panel/keyboard-panel.vue')['default']
    MartingaleBetting: typeof import('./../components/martingale-betting/martingale-betting.vue')['default']
    MessageItem: typeof import('./../components/message-item/message-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YwzChart: typeof import('./../components/three-line-pic/src/YwzChart.vue')['default']
    YwzForm: typeof import('./../components/ywz-form/src/YwzForm.vue')['default']
    YwzTable: typeof import('./../components/ywz-table/src/YwzTable.vue')['default']
  }
}
